mode: online # (online, offline). Offline uses more memory
checkpoint_path: "deps/co-tracker/checkpoints/cotracker2v1.pth"
grid_size: 30
window_len: 16
render_all: false
displacement_threshold: null
max_moving_points: null
linewidth: 5
overwrite: true